### ISSUE TITLE
HTTP Error 406 when requesting system-tasks from web browser

### ISSUE THREAD

**Issue by FrancoisCamus** [thymeflow/thymeflow-back#1]
The value for access-control-allow-origin header returned for a request to http://localhost:8080/system-tasks is http://localhost:4200.
I therefore get a 406 HTTP error from a web browser.

Here are the headers received:

![issue_1_response_headers](https://cloud.githubusercontent.com/assets/7439901/18628811/5a12f61a-7e62-11e6-999a-5fd237153e33.PNG)

And the error in the web browser:

![issue_1_web_browser_error](https://cloud.githubusercontent.com/assets/7439901/18628812/5a2a14a8-7e62-11e6-95c6-9bb26acb6722.PNG)

**Comment by masda70** [comment]
Please configure the `thymeflow.http.frontend-uri` key to fit your needs.

By default, it's set to "http://localhost:4200". You can only configure one origin at the moment.

**Comment by FrancoisCamus** [comment]
Alright! Is that still an issue that we want to address or should we close?

**Comment by masda70** [comment]
We should address this at some point. I think a "thymeflow.http.allowed-origins" key should be added, and when not provided, only "thymeflow.http.frontend-uri" is the allowed origin.

**Comment by FrancoisCamus** [comment]
I don't think the error comes from that. I'm still having it. I'll show you when you are around.

**Comment by FrancoisCamus** [comment]
The issue came from the front-end. The front-end was waiting for a response in the json api format.
