### ISSUE TITLE
Json api data attribute names should be dasherized and not camelized

### ISSUE THREAD

**Issue by FrancoisCamus** [thymeflow/thymeflow-back#2]
For system-task, startDate attribute should be start-date

**Comment by masda70** [comment]
True. Although client-side expectations can be easily changed by extending the JSONAPISerializer. 

By default they are set to:

```
  keyForAttribute(key, method) {
    return dasherize(key);
  },
  keyForRelationship(key, typeClass, method) {
    return dasherize(key);
  }
```

The naming conventions are not defined by the JSON API spec, so it's up to us.

I would say the server side effort will be more involved right now and in the near future, so I would prefer we would do it client-side.

**Comment by FrancoisCamus** [comment]
Yep I already have a temporary fix that I can commit.

On the backend, you'll still want to dissociate java class property names from the json generated by your serializer to avoid breaking client-server communication when refactoring the backend (renaming a property...). You should be able to decorate your class properties to tell the serializer what name it should use for a given property.

**Comment by FrancoisCamus** [comment]
Modify https://github.com/thymeflow/thymeflow-front/commit/307ccc3828a61c7db31777d9abb8cea4db13a94b when fixed

**Comment by masda70** [comment]
Closing, camelCase will be used by the JSON API for now.
